
package com.cpn.os4j.model;

import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class ExternalGatewayInfo
    implements Serializable
{

    @JsonProperty("network_id")
    private String networkId;
    private final static long serialVersionUID = 2751795901730690399L;

    public ExternalGatewayInfo() {
    }

    public String getNetworkId() {
        return networkId;
    }

    public void setNetworkId(final String aNetworkId) {
        this.networkId = aNetworkId;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("networkId", networkId).toString();
    }

}
