
package com.cpn.os4j.model;

import java.io.Serializable;
import javax.persistence.OneToOne;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class Fixedips
    implements Serializable
{

    @JsonProperty("subnet_id")
    private String subnetId;
    @JsonProperty("ip_address")
    private String ipAddress;
    private final static long serialVersionUID = 776828410057581966L;

    public Fixedips() {
    }

    public String getSubnetId() {
        return subnetId;
    }

    public void setSubnetId(final String aSubnetId) {
        this.subnetId = aSubnetId;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(final String anIpAddress) {
        this.ipAddress = anIpAddress;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("subnetId", subnetId).append("ipAddress", ipAddress).toString();
    }

}
