
package com.cpn.os4j.model;

import java.io.Serializable;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class Floatingip
    implements Serializable
{
    private String floatingNetworkId;
    private String tenantId;
    private String fixedIpAddress;
    private String floatingIpAddress;
    private String id;
    private String portId;
    private String routerId;
    private final static long serialVersionUID = 7799287859101738205L;

    public Floatingip() {
    }
    public String getFloatingNetworkId() {
        return floatingNetworkId;
    }
    @JsonProperty("floating_network_id")
    public void setFloatingNetworkId(final String aFloatingNetworkId) {
        this.floatingNetworkId = aFloatingNetworkId;
    }
    public String getTenantId() {
        return tenantId;
    }
    @JsonProperty("tenant_id")
    public void setTenantId(final String aTenantId) {
        this.tenantId = aTenantId;
    }
    @JsonIgnore
    public String getFixedIpAddress() {
        return fixedIpAddress;
    }
    @JsonProperty("fixed_ip_address")
    public void setFixedIpAddress(final String aFixedIpAddress) {
        this.fixedIpAddress = aFixedIpAddress;
    }
    @JsonIgnore
    public String getFloatingIpAddress() {
        return floatingIpAddress;
    }
    @JsonProperty("floating_ip_address")
    public void setFloatingIpAddress(final String aFloatingIpAddress) {
        this.floatingIpAddress = aFloatingIpAddress;
    }
    @JsonIgnore
    public String getId() {
        return id;
    }
    @JsonProperty("id")
    public void setId(final String anId) {
        this.id = anId;
    }
    @JsonIgnore
    public String getPortId() {
        return portId;
    }
    @JsonProperty("port_id")
    public void setPortId(final String aPortId) {
        this.portId = aPortId;
    }
    @JsonIgnore
    public String getRouterId() {
        return routerId;
    }
    @JsonProperty("router_id")
    public void setRouterId(final String aRouterId) {
        this.routerId = aRouterId;
    }
    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("floatingNetworkId", floatingNetworkId).append("tenantId", tenantId).append("fixedIpAddress", fixedIpAddress).append("floatingIpAddress", floatingIpAddress).append("id", id).append("portId", portId).append("routerId", routerId).toString();
    }

}
