
package com.cpn.os4j.model;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class IPRange
    implements Serializable
{

    private String start;
    private String end;
    private final static long serialVersionUID = 8393077330735767775L;

    public IPRange() {
    }

    public String getStart() {
        return start;
    }

    public void setStart(final String aStart) {
        this.start = aStart;
    }

    public String getEnd() {
        return end;
    }

    public void setEnd(final String anEnd) {
        this.end = anEnd;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("start", start).append("end", end).toString();
    }

}
