
package com.cpn.os4j.model;

import java.io.Serializable;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class Metadata
    implements Serializable
{

    @JsonProperty("is_admin")
    private Integer isAdmin;
    private List<String> roles;
    private final static long serialVersionUID = 7497872532458541248L;

    public Metadata() {
    }

    public Integer getIsAdmin() {
        return isAdmin;
    }

    public void setIsAdmin(final Integer anIsAdmin) {
        this.isAdmin = anIsAdmin;
    }

    public List<String> getRoles() {
        return roles;
    }

    public void setRoles(final List<String> someRoles) {
        this.roles = someRoles;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("isAdmin", isAdmin).append("roles", roles).toString();
    }

}
