
package com.cpn.os4j.model;

import java.io.Serializable;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class Router
    implements Serializable
{

    @JsonIgnore
	private String status;
    private String name;
  
    private Boolean adminStateUp;
    private String tenantId;
    private String id;
    @JsonProperty("external_gateway_info")
    private ExternalGatewayInfo externalGatewayInfo;
    private final static long serialVersionUID = 377025078575909614L;

    public Router() {
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(final String aStatus) {
        this.status = aStatus;
    }
    @JsonIgnore
    public String getName() {
        return name;
    }
    @JsonProperty("name")
    public void setName(final String aName) {
        this.name = aName;
    }
    @JsonIgnore
    public Boolean getAdminStateUp() {
        return adminStateUp;
    }
    @JsonProperty("admin_state_up")
    public void setAdminStateUp(final Boolean anAdminStateUp) {
        this.adminStateUp = anAdminStateUp;
    }
    @JsonIgnore
    public String getTenantId() {
        return tenantId;
    }
    @JsonProperty("tenant_id")
    public void setTenantId(final String aTenantId) {
        this.tenantId = aTenantId;
    }
    @JsonIgnore
    public String getId() {
        return id;
    }
    @JsonProperty("id")
    public void setId(final String anId) {
        this.id = anId;
    }

    public ExternalGatewayInfo getExternalGatewayInfo() {
        return externalGatewayInfo;
    }

    public void setExternalGatewayInfo(final ExternalGatewayInfo anExternalGatewayInfo) {
        this.externalGatewayInfo = anExternalGatewayInfo;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("status", status).append("name", name).append("adminStateUp", adminStateUp).append("tenantId", tenantId).append("id", id).append("externalGatewayInfo", externalGatewayInfo).toString();
    }

}
